### ISSUE TITLE
CSFD 

### ISSUE THREAD

**Issue by luxorko** [digiteng/xtra#7]
Could you add search from CSFD please? -ist CZ-SK movie database
API should be using from android.
"https://github.com/skyjet18/enigma2-plugin-extensions-csfd"

**Comment by luxorko** [comment]
donate - where and how much?

**Comment by digiteng** [comment]
I didn't see your previous message, sorry...
if you still want it, 50euro
https://wise.com/
You can send it through the site...no paypal unfortunately...
I'll attach screenshots if you're going to donate...
good day...


luxorko ***@***.***>, 3 Mar 2022 Per, 13:33 tarihinde şunu
yazdı:
